// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydpvrgtaebcvtyhszann.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkcHZyZ3RhZWJjdnR5aHN6YW5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3NzE2ODQsImV4cCI6MjA1NjM0NzY4NH0.K5Yj6UdazSpXGAy2jmy4SRAPVDTC6ZbVYy51EnOgP-0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);